version: '3.3'

services:
  app:
    image: 'sapergis/movierama:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

     
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: db
    expose:
      - "5432"
    environment:
      - POSTGTES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password


